Updated deployment workflow

diff --git a/.github/workflows/deploy_to_github_pages.yml b/.github/workflows/deploy_to_github_pages.yml
--- a/.github/workflows/deploy_to_github_pages.yml
+++ b/.github/workflows/deploy_to_github_pages.yml
@@ -1,8 +1,20 @@
+# =========== IMPORTANT!! READ THIS!! ============ #
+# This file can be copied to be used in other websites deployments.
+# When you copy this file, make sure to check and modify the fields
+# that here are marked with `MODIFY IF NEEDED`.
+
+# Other related files/folders that you will also need to copy:
+#    - .github/workflows/templates/pr_previews_page.html
+#    - .github/workflows/delete_pr_preview.yml
+# ============================================== #
+
 name: Deploy to GitHub Pages
 on:
   push: #Action fires anytime there is a push to the following branches
     branches:
       - main
+    paths:
+      - 'documentation/**' # MODIFY IF NEEDED - This should be changed to be DOC_DIR/** based on the env variable DOC_DIR below
   pull_request: #Action also fires anytime a PR is (re)opened, closed or synchronized
     types:
       - opened
@@ -11,36 +23,51 @@ on:
   workflow_dispatch: #Action can also be triggered manually
 env:
   TZ: Australia/Canberra
-  DOC_DIR: 'documentation'
+  DOC_DIR: 'documentation' # MODIFY IF NEEDED - Directory where the mkdocs.yml file is located relative to the repository root
+  BUILD_DEVELOPMENT_WEBSITE: false # MODIFY IF NEEDED - Set to 'true' to build also the development website from the 'development' branch
   BUILD_DIR: ${{ github.workspace }}/website-build
   WEBSITE_DIR: ${{ github.workspace }}/full-website
-  ROOT_DOMAIN: https://access-ram3-configs.access-hive.org.au/
   PR_PREVIEWS_DIR: pr-previews
+  PR_PREVIEW_EXCLUDE_REGEX: ^!no-(pr-)?preview\b # This regex will be considered case insensitive
+  PR_PREVIEW_COMMENT_LABEL: pr-preview-comment
 concurrency:
   group: documentation-build-deploy
   cancel-in-progress: true
 
+  # ========== You should not need to modify anything below this ============ #
+
 jobs:
-  # Set the root url to be used at build time to set the SITE_URL env variable
+  # The conditionals cannot depend directly from the GitHub environment (e.g., if: env.BUILD_DEVELOPMENT_WEBSITE == 'true') 
+  # so we use a job to set that as an output that can be then used in the other jobs' conditionals
+  set-development-preview-condition:
+    name: Set development preview build condition
+    runs-on: ubuntu-latest
+    outputs:
+      build_development_website: ${{ steps.set-condition.outputs.build_development_website }}
+    steps:
+      - name: Set condition
+        id: set-condition
+        run: echo "build_development_website=${{ env.BUILD_DEVELOPMENT_WEBSITE }}" >> $GITHUB_OUTPUT
+
+  # Get the root url to be used at build time to set the SITE_URL env variable
   # used in the mkdocs.yml file to construct the website map for links
-  set-root-url:
+  get-root-url:
     name: Set root URL
     runs-on: ubuntu-latest
     outputs:
-      root_url: ${{ steps.set-root-url.outputs.root_url }}
+      root_url: ${{ steps.get-root-url.outputs.root_url }}
+    env:
+      GH_TOKEN: ${{ github.token }} # Required for gh usage
     steps:
-      - name: Set root url
-        id: set-root-url
+      - name: Get root url
+        id: get-root-url
         run: |
-          root_domain=$(sed 's:/*$::' <<< '${{ env.ROOT_DOMAIN }}') # Remove trailing slash if present
-          if [[ "$root_domain" == https://access-nri.github.io ]]; then
-            # If the domain is the default GitHub pages one (not a custom one), the website will be deployed 
-            # as a GitHub Pages Project Site with the URL in the format http://<username>.github.io/<repository>/
-            root_url=${root_domain}/${{ github.event.repository.name }}/
-          else
-            root_url=${root_domain}/
+          root_url=$(gh api repos/${{ github.repository }}/pages --jq '.html_url')
+          if [[ $? != 0 ]]; then
+            echo "::error::The repository '${{ github.repository }}' does not seem to gave a GitHub Pages deployment."
+            exit 1
           fi
-          echo "Root url set to ${root_url}"
+          echo "Root url set to '${root_url}'"
           echo "root_url=${root_url}" >> $GITHUB_OUTPUT
   
   # Get the date to be used in the PR preview comments
@@ -74,20 +101,20 @@ jobs:
     steps:
       - name: Add PR preview setup comment
         if: ${{ github.event.action != 'closed' }}
-        uses: access-nri/actions/.github/actions/comment@davide/add_comment_logs
+        uses: access-nri/actions/.github/actions/comment@main
         with:
           message: |
-            PR Preview
-            :---:
-            🛫 The preview of PR head commit [${{ env.HEAD }}](${{ env.HEAD_URL }}) is currently being deployed.<br>The preview URL will be available once the deployment completes.<br>For further details, please check the [Actions](https://github.com/${{ github.repository }}/actions) tab.
-            ${{ needs.get-date.outputs.date }}
-          label: ${{ vars.PR_PREVIEW_COMMENT_LABEL }}
+           PR Preview
+           :---:
+           🛫 The preview of PR head commit [${{ env.HEAD }}](${{ env.HEAD_URL }}) is currently being deployed.<br>The preview URL will be available once the deployment completes.<br>For further details, please check the [Actions](https://github.com/${{ github.repository }}/actions) tab.
+           ${{ needs.get-date.outputs.date }}
+          label: ${{ env.PR_PREVIEW_COMMENT_LABEL }}
 
 #   Build the main website
   build-main:
     name: Build main website
     runs-on: ubuntu-latest
-    needs: set-root-url
+    needs: get-root-url
     env:
       GH_TOKEN: ${{ github.token }} # Required for gh usage
     steps:
@@ -103,7 +130,7 @@ jobs:
           if [[ -f mkdocs.yml ]]; then
             echo "mkdocs.yml file found."
           else
-            echo "::warning::No ${{ env.DOC_DIR }}/mkdocs.yml file found in '$(git rev-parse --abbrev-ref HEAD)'."
+            echo "::warning::No mkdocs.yml file found in '$(git rev-parse --abbrev-ref HEAD)'."
             echo "SKIP_STEP=true" >> $GITHUB_ENV
           fi
 
@@ -123,7 +150,7 @@ jobs:
         working-directory: ${{ env.DOC_DIR }}
         env:
           GH_TOKEN: ${{ github.token }} # Required for gh usage
-          ROOT_URL: ${{ needs.set-root-url.outputs.root_url }}
+          ROOT_URL: ${{ needs.get-root-url.outputs.root_url }}
         id: build
         if: ${{ ! env.SKIP_STEP }}
         run: |
@@ -140,17 +167,74 @@ jobs:
           name: main-website
           path: ${{env.BUILD_DIR}}
   
+# Build the development website
+  build-development:
+    name: Build development website
+    runs-on: ubuntu-latest
+    needs: [set-development-preview-condition,get-root-url]
+    if: ${{ needs.set-development-preview-condition.outputs.build_development_website == 'true' }}
+    env:
+      GH_TOKEN: ${{ github.token }} # Required for gh usage
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          ref: development
+
+      - name: Check mkdocs.yaml
+        id: check-mkdocs
+        run: |
+          if [[ -f mkdocs.yml ]]; then
+            echo "mkdocs.yml file found."
+          else
+            echo "::warning::No mkdocs.yml file found in '$(git rev-parse --abbrev-ref HEAD)'."
+            echo "SKIP_STEP=true" >> $GITHUB_ENV
+          fi
+
+      - name: Python setup
+        uses: actions/setup-python@v5
+        if: ${{ ! env.SKIP_STEP }}
+        with:
+          python-version: 3.11.x
+
+      - name: Install dependencies
+        working-directory: ${{ env.DOC_DIR }}
+        if: ${{ ! env.SKIP_STEP }}
+        run: |
+          pip install -r requirements.txt
+
+      - name: Build website
+        working-directory: ${{ env.DOC_DIR }}
+        env:
+          GH_TOKEN: ${{ github.token }} # Required for gh usage
+          ROOT_URL: ${{ needs.get-root-url.outputs.root_url }}
+        id: build
+        if: ${{ ! env.SKIP_STEP }}
+        run: |
+            dir=development-website
+            site_url="${{ env.ROOT_URL }}${dir:+${dir}/}"
+            command="SITE_URL=${site_url} mkdocs build -f mkdocs.yml -d ${{env.BUILD_DIR}}"
+            echo "$command"
+            eval "$command"
+     
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        if: ${{ ! env.SKIP_STEP }}
+        with:
+          name: development-website
+          path: ${{env.BUILD_DIR}}
+
   # Get information about open PRs to be used to build websites 
   # for the PR previews and to setup the PR-previews comments
   get-prs-info:
     name: Get PRs info
     runs-on: ubuntu-latest
-    needs: set-root-url
+    needs: get-root-url
     outputs:
       open_prs_info: ${{ steps.get-prs-info.outputs.open_prs_info }}
     env:
       GH_TOKEN: ${{ github.token }} # Required for gh usage
-      ROOT_URL: ${{ needs.set-root-url.outputs.root_url }}
+      ROOT_URL: ${{ needs.get-root-url.outputs.root_url }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -159,22 +243,29 @@ jobs:
         id: get-prs-info
         working-directory: ${{ env.DOC_DIR }}
         run: |
-          # Include only open PRs whose head branch is not `main`
+          # Include only open PRs, not from forks, and whose head branch is not `main`
           open_prs=$(
             gh pr list \
             --state open \
-            --json number,title,headRefOid \
-            --jq 'sort_by(.number) | .[] | select( .headRefName!="main" )' \
+            --json number,title,headRepositoryOwner,headRefOid,body \
+            --jq 'sort_by(.number) | .[] | select( .headRefName!="main" and .headRepositoryOwner.login=="ACCESS-NRI")' \
           )
           
           # If open PRs are found, filter them and output the desired json object
           if [[ -n "$open_prs" ]]; then
-            # Keep only PRs with a mkdocs.yml file in their head commit
-            prs_with_mkdocs=$(
-              while read pr; do
+            # Keep only PRs:
+            # - with a mkdocs.yml file in their head commit
+            # - whose body doesn't start with a PR_PREVIEW_EXCLUDE_REGEX line
+            filtered_prs=$(
+              while IFS= read -r pr; do
                 sha=$(jq -r '.headRefOid' <<< $pr)
-                if gh api repos/${{ github.repository }}/git/trees/${sha}?recursive=1 | \
-                jq '.tree[].path' | grep 'mkdocs.ya\?ml' > /dev/null; then 
+                body=$(jq -r '.body' <<< $pr)
+                if (
+                  gh api repos/${{ github.repository }}/git/trees/${sha}?recursive=1 | \
+                  jq '.tree[].path' | grep 'mkdocs.ya\?ml' > /dev/null
+                ) && (
+                  ! grep -qi '${{ env.PR_PREVIEW_EXCLUDE_REGEX }}' <<< "$body"
+                ); then 
                   echo $pr
                 fi
               done <<< "$open_prs"
@@ -191,7 +282,7 @@ jobs:
               pr_title: .title, 
               pr_head_sha: .headRefOid, 
               pr_preview_url: ("${{ env.ROOT_URL }}${{ env.PR_PREVIEWS_DIR }}/" + (.number | tostring))
-              }]' <<< "$prs_with_mkdocs"
+              }]' <<< "$filtered_prs"
             )
             
             echo "Found the following open PRs:"
@@ -205,7 +296,7 @@ jobs:
   build-pr:
     name: Build PR ${{matrix.pr_number}}
     runs-on: ubuntu-latest
-    needs: [set-root-url, get-prs-info]
+    needs: [get-root-url, get-prs-info]
     # Run this job only if there are open PRs
     if: ${{ needs.get-prs-info.outputs.open_prs_info != '' }}
     env:
@@ -234,7 +325,7 @@ jobs:
         working-directory: ${{ env.DOC_DIR }}
         env:
           GH_TOKEN: ${{ github.token }} # Required for gh usage
-          ROOT_URL: ${{ needs.set-root-url.outputs.root_url }}
+          ROOT_URL: ${{ needs.get-root-url.outputs.root_url }}
         id: build
         run: |
           dir=$(sed 's|^${{ env.ROOT_URL }}||' <<< ${{ matrix.pr_preview_url }})
@@ -253,7 +344,7 @@ jobs:
   create-pr-previews-page:
     name: Create PR previews list page
     runs-on: ubuntu-latest
-    needs: [set-root-url, get-prs-info]
+    needs: [get-root-url, get-prs-info]
     env:
       GH_TOKEN: ${{ github.token }} # Required for gh usage
       FILE_NAME: index.html
@@ -271,7 +362,13 @@ jobs:
 
       - name: Create PR previews page
         run: |
-          printf '{"data": %s}' '${{ needs.get-prs-info.outputs.open_prs_info }}' | \
+          open_prs_json='${{ needs.get-prs-info.outputs.open_prs_info }}'
+          if [[ -z "$open_prs_json" ]]; then
+            data_json=$(jq -c -n --argjson data "$open_prs_json" '{"data": $data}')
+          else
+            data_json='{}'
+          fi
+          jq -c <<< "$data_json" | \
             jinja -d - -f json ./.github/workflows/templates/pr_previews_page.html > ${{ env.FILE_NAME }}
           echo "Created the pr-previews page through the following html file:"
           cat ${{ env.FILE_NAME }}
@@ -286,9 +383,9 @@ jobs:
   set-website-structure:
     name: Set entire website structure
     runs-on: ubuntu-latest
-    needs: [build-main, build-pr]
-    # Run this job also if build-pr was skipped because no PR was found
-    if: ${{ contains(fromJson('["success","skipped"]'), needs.build-pr.result) }}
+    needs: [build-main, build-development, build-pr, create-pr-previews-page]
+    # Run this job also if build-pr or build-development was skipped (no PR was found or no development build requested)
+    if: ${{ always() && contains(fromJson('["success","skipped"]'), needs.build-pr.result) && contains(fromJson('["success","skipped"]'), needs.build-development.result) }}
     env:
       GH_TOKEN: ${{ github.token }} # Required for gh usage
     steps:
@@ -311,7 +408,7 @@ jobs:
           # Set permissions
           chmod -c -R +rX ${{ env.WEBSITE_DIR }}
           echo "Website structure set to:"
-          tree -d -L 3  ${{ env.WEBSITE_DIR }}
+          tree -d -L 2  ${{ env.WEBSITE_DIR }}
 
       - name: Create artifact for deployment to GitHub Pages
         uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa #v3.0.1
@@ -322,6 +419,10 @@ jobs:
   deploy:
     needs: set-website-structure
     runs-on: ubuntu-latest
+    # Need to specify this conition because otherwise this job might be skipped if
+    # any job needed by this job's needed job(s) is skipped (e.g., if a job needed by set-website-structure is skipped)
+    # Reference: https://github.com/actions/runner/issues/2205
+    if: ${{ always() && needs.set-website-structure.result == 'success' }}
     permissions:
       pages: write # to deploy to Pages
       id-token: write # to verify the deployment originates from an appropriate source
@@ -333,7 +434,7 @@ jobs:
   pr-preview:
     needs: [get-date, get-prs-info, deploy]
     # Run this job only if there are open PRs
-    if: ${{ needs.get-prs-info.outputs.open_prs_info != '' }}
+    if: ${{ always() && needs.deploy.result == 'success' && needs.get-prs-info.outputs.open_prs_info != '' }}
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -343,7 +444,7 @@ jobs:
       pull-requests: write
     steps:
       - name: Add PR preview setup comment
-        uses: access-nri/actions/.github/actions/comment@davide/add_comment_logs
+        uses: access-nri/actions/.github/actions/comment@main
         with:
           message: |
             PR Preview
@@ -352,7 +453,7 @@ jobs:
             ${{ needs.get-date.outputs.date }}
             Preview generated through the _${{ github.workflow }}_ workflow run [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
           number: ${{ matrix.pr_number }}
-          label: ${{ vars.PR_PREVIEW_COMMENT_LABEL }}
+          label: ${{ env.PR_PREVIEW_COMMENT_LABEL }}
 
   failed-preview:
     needs: [get-date, pr-preview]
@@ -363,7 +464,7 @@ jobs:
       pull-requests: write
     steps:
       - name: Add PR preview failure comment
-        uses: access-nri/actions/.github/actions/comment@davide/add_comment_logs
+        uses: access-nri/actions/.github/actions/comment@main
         with:
           message: |
             PR Preview
@@ -371,4 +472,4 @@ jobs:
             ⚠️ There was an error in the pr-preview deployment.
             For more information check the [Actions](https://github.com/${{github.repository}}/actions) tab.
             ${{ needs.get-date.outputs.date }}
-          label: ${{ vars.PR_PREVIEW_COMMENT_LABEL }}
+          label: ${{ env.PR_PREVIEW_COMMENT_LABEL }}
